version: '3'

services:
  # 后端服务
  temperature-backend:
    build:
      context: ./temperature_project_java
    container_name: temperature-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    restart: unless-stopped

  # 前端服务
  temperature-frontend:
    build:
      context: ./temperature-frontend
    container_name: temperature-frontend
    ports:
      - "80:80"
    depends_on:
      - temperature-backend
    restart: unless-stopped 